---
- name: Attacher le serveur a Satellite
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Inclure les variables
      include_vars: vars/rhpds-sat-var.yml

    - name: Nettoyer le contenu de yum.repos.d
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/etc/yum.repos.d/*"

    - name: Installer l'agent Katello
      yum:
        disable_gpg_check: yes
        name: "{{ katello_path }}"
        state: present

    - name: Enregistrement a Satellite avec la cle d'activation
      redhat_subscription:
        state: present
        activationkey: "{{ var_activationkey }}"
        org_id: "{{ var_org_id }}"
