- name: Basic Play
  hosts: "{{ vmname }}"
  become: yes
  become_method: sudo

  tasks:
    - name: Installer les packages
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - php
#        - php-mysql
#        - libsemanage-python
#        - firewalld

    - name: Activer httpd
      service:
        name: httpd
        enabled: yes
        state: started
