# vim:se ft=ansible
# Replace all with group name to match your needs.
- hosts: "{{ vmweb }}"
  become: yes
  become_method: sudo

  name: Installer l'application
  tasks:
#    - name: Installer les packages
#      yum: name={{ item }} state=latest
#      with_items:
#        - httpd
#        - php
#        - php-mysql
#        - libsemanage-python
#        - firewalld
    - name: Installer la page index.php
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
        backup: yes

    - name: Installer l'application
      copy: src={{ item }} dest=/var/www/html
      with_fileglob:
              - ../files/fonts/
              - ../files/*

    - name: Ouvrir les ports du firewall
      firewalld: "port={{ item }}/tcp state=enabled zone=public permanent=yes immediate=true"
      with_items:
        - 80
        - 443

    - name: Configurer SELinux
      seboolean:
        state: yes
        name: httpd_can_network_connect
        persistent: yes

    - name: Activer httpd
      service:
        name: httpd
        enabled: yes
        state: started


# Replace host with the group name to match your needs.
- hosts: "{{ vmdb }}"
  become: yes
  become_method: sudo

  name: Installer la base de données
  vars:
        dbname: "dbname"
        dbuser: "dbusername"
        dbpass: "dbpass"
  tasks:
#    - name: Installer les packages
#      yum: name="{{ item }}" state=latest
#      with_items:
#        - mariadb
#        - mariadb-server
#        - MySQL-python
#        - php-mysql
#        - firewalld
    - name: Ouvrir les ports du firewall
      firewalld:
        state: enabled
        zone: public
        immediate: yes
        service: mysql
        permanent: yes

    - name: Configurer MariaDB
      template:
        src: etc_my.cnf.d_network.cnf.j2
        dest: /etc/my.cnf.d/network.cnf
        backup: yes

    - name: Activer MariaDB
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: Créer la base de données
      mysql_db:
        name: '{{ dbname }}'
        encoding: utf8
        state: present

    - name: Créer les utilisateurs de la base de données.
      mysql_user:
        name: '{{ dbuser }}'
        state: present
        host: '%'
        password: '{{ dbpass }}'
        priv: '*.*:ALL'
