- name: Deploy Db
  hosts: all
  become: yes
  become_method: sudo
  vars:
        dbname: "dbname"
        dbuser: "dbusername"
        dbpass: "dbpass"

  tasks:
    - name: Add default gateway
      shell: ip route add 0.0.0.0/0 via 192.168.0.2

    - name: Clean old repo
      shell: rm -f /etc/yum.repos.d/cd.repo

    - name: Subcription-manager
      redhat_subscription:
        state: present
        org_id: "5318211"
        activationkey: "demo-cloud-day"

    - name: Disable all repos
      shell: subscription-manager repos --disable=*

    - name: Enable Repo rhel-7-server-rpms
      shell: subscription-manager repos --enable=rhel-7-server-rpms

    - name: Enable Repo rhel-7-server-rh-common-rpms
      shell: subscription-manager repos --enable=rhel-7-server-rh-common-rpms

    - name: Enable Repo rhel-7-server-extras-rpms
      shell: subscription-manager repos --enable=rhel-7-server-extras-rpms

    - name: Enable Repo rhel-7-server-supplementary-rpms
      shell: subscription-manager repos --enable=rhel-7-server-supplementary-rpms


    - name: Installer les packages
      yum: name="{{ item }}" state=latest
      with_items:
        - mariadb
        - mariadb-server
        - MySQL-python
        - php-mysql
        - firewalld

    - name: Ouvrir les ports du firewall
      firewalld:
        state: enabled
        zone: public
        immediate: yes
        service: mysql
        permanent: yes

    - name: Configurer MariaDB
      template:
        src: etc_my.cnf.d_network.cnf.j2
        dest: /etc/my.cnf.d/network.cnf
        backup: yes

    - name: Activer MariaDB
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: Créer la base de données
      mysql_db:
        name: '{{ dbname }}'
        encoding: utf8
        state: present

    - name: Créer les utilisateurs de la base de données.
      mysql_user:
        name: '{{ dbuser }}'
        state: present
        host: '%'
        password: '{{ dbpass }}'
        priv: '*.*:ALL'
